In [1]:
import itertools
import numpy as np
A = np.array([[1,2,3], [2,3,4], [1,1,1]])
B = np.array([[4,5,6], [7,8,9], [4,5,7]])
C = np.array([[1,2], [2,3], [1,1]])

In [2]:
print("A: \n", A)
print("B: \n", B)
print("C: \n", C)
print("A+B: \n", A+B)
print("B-A: \n", B-A)

A: 
 [[1 2 3]
 [2 3 4]
 [1 1 1]]
B: 
 [[4 5 6]
 [7 8 9]
 [4 5 7]]
C: 
 [[1 2]
 [2 3]
 [1 1]]
A+B: 
 [[ 5  7  9]
 [ 9 11 13]
 [ 5  6  8]]
B-A: 
 [[3 3 3]
 [5 5 5]
 [3 4 6]]


In [3]:
def matmul(A,B):
    assert A.shape[1] == B.shape[0], "Oh no, check matrices shape"
    result_items = []
    for k in A:
        for m in B.T:
            result_items.append(np.sum(k*m))
    return np.array(result_items).reshape(A.shape[0], B.shape[1])

In [4]:
print("B*C: \n", matmul(B,C))
print("B*C check:", (matmul(B,C)==np.matmul(B,C)).ravel().all())
print("C*A:")
print(matmul(C,A))

B*C: 
 [[20 29]
 [32 47]
 [21 30]]
B*C check: True
C*A:


AssertionError: Oh no, check matrices shape

$M^n$ nth power of a square matrix without diagonalization. $M^{100}$ below: $\\ $
This only works for $M \in \{0,1\}$ with only 1 change in the non-main diagonal. Check my other notebook for eigen approach.

In [5]:
M = np.array([[1,1,0], [0,1,0], [0,0,1]])

In [6]:
def m_power(M,n): 
    d = matmul(M,M) - M
    a = np.zeros(M.shape)
    np.fill_diagonal(a, np.diag(M))
    return a + (d * n)

In [7]:
n = 100
display(M)
display(m_power(M, n))
k = M.copy()
for _ in range(n-1):
    k = matmul(k, M)
display(k)

array([[1, 1, 0],
       [0, 1, 0],
       [0, 0, 1]])

array([[  1., 100.,   0.],
       [  0.,   1.,   0.],
       [  0.,   0.,   1.]])

array([[  1, 100,   0],
       [  0,   1,   0],
       [  0,   0,   1]])

Determinant of a matrix:
$\\ |A| = \begin{vmatrix}
a & b \\
c & d
\end{vmatrix} = ad - bc$
$\\ $
$ |A| = \begin{vmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
\end{vmatrix} = a(ei - fh) - b(di - fg) + c(dh - eg)  $

In [8]:
def det(M):
    assert M.shape[0] == M.shape[1], "Oh no, non-square!"
    if M.shape == (2,2): return det_two_two(M)
    D = 0
    for x in list(itertools.product(range(M.shape[0]), range(M.shape[1])))[:M.shape[0]]:
        sub_D = np.delete(np.delete(M, x[0], axis=0), x[1], axis=1)
        el = M[x[0], x[1]] * {0 : 1, 1: -1}[x[1] % 2]
        D += el * (det_two_two(sub_D) if sub_D.shape == (2,2) else det(sub_D))
    return D

def det_two_two(M):
    assert M.shape == (2,2), "Oh no, not 2x2"
    return np.diag(M, 0).prod() - (np.diag(M, 1) * np.diag(M, -1))[0]

In [9]:
M = np.array([[13,0,-2, 4], [2,1,0,5], [2,3,3,12], [1,2,3,4]])
print(M)
print(det(M))
print(np.linalg.det(M))

[[13  0 -2  4]
 [ 2  1  0  5]
 [ 2  3  3 12]
 [ 1  2  3  4]]
-99
-98.99999999999999


Adjugate of a 2x2 matrix:
$\\ A = \begin{vmatrix}
a & b \\
c & d
\end{vmatrix}; \\ adj(A) = \begin{vmatrix}
d & -b \\
-c & a
\end{vmatrix}$

In [10]:
def adj(M):
    assert M.shape == (2,2), "Only for 2x2 matrices"
    reverse_diag = np.diag(M,0)[::-1]
    M = M * -1
    np.fill_diagonal(M, reverse_diag)
    return M
M = np.random.randint(5, size=(2,2))
print(M)
print(adj(M))

[[1 4]
 [2 1]]
[[ 1 -4]
 [-2  1]]


In [11]:
def inverse(M):
    return 1 / det(M) * adj(M)
A = np.array([[2, 1], [-5, 3]])
print(inverse(A))
print(np.linalg.inv(A))
print(matmul(A, inverse(A)).round(0))

[[ 0.27272727 -0.09090909]
 [ 0.45454545  0.18181818]]
[[ 0.27272727 -0.09090909]
 [ 0.45454545  0.18181818]]
[[1. 0.]
 [0. 1.]]


Simple linear equation: $\\ 2x  + 1y = 15 \\ -5x + 3y = 10$ 

In [12]:
A = np.array([[2, 1], [-5, 3]])
B = np.array([15, 10])
solution = inverse(A) @ B
print(solution)
print((solution * A).sum(axis=1))

[3.18181818 8.63636364]
[15. 10.]
